In [11]:
import pandas as pd
import numpy as np
df = pd.read_csv("Strategic_Subject_List.csv")

//anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
df.head(100)

SSL SCORE PREDICTOR RAT AGE AT LATEST ARREST  \
0         343                              20-30   
1         388                       less than 20   
2         320                              20-30   
3         382                              20-30   
4         316                              20-30   
5         364                              20-30   
6         362                              20-30   
7         356                              20-30   
8         310                              20-30   
9         355                       less than 20   
10        354                       less than 20   
11        353                              20-30   
12        352                              20-30   
13        351                              20-30   
14        350                       less than 20   
15        350                              20-30   
16        349                              20-30   
17        306                              20-30   
18        306                              20-30   
19        346                       less than 20   
20        345                       less than 20   
21        345                              20-30   
22        331                              20-30   
23        343                              20-30   
24        306                              20-30   
25        342                              20-30   
26        306                              20-30   
27        306                              20-30   
28        342                              20-30   
29        341                              20-30   
..        ...                                ...   
70        333                       less than 20   
71        333                              20-30   
72        333                              20-30   
73        332                              20-30   
74        332                       less than 20   
75        331                              20-30   
76        331                              20-30   
77        331                              20-30   
78        306                              20-30   
79        306                              20-30   
80        331                       less than 20   
81        330                              20-30   
82        330                       less than 20   
83        330                              20-30   
84        330                              20-30   
85        330                              20-30   
86        328                              20-30   
87        327                              20-30   
88        327                              20-30   
89        327                              20-30   
90        327                       less than 20   
91        327                              20-30   
92        326                       less than 20   
93        326                              20-30   
94        305                              20-30   
95        325                              20-30   
96        323                              20-30   
97        322                              20-30   
98        322                       less than 20   
99        322                              20-30   

    PREDICTOR RAT VICTIM SHOOTING INCIDENTS  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   
5                                         0   
6                                         0   
7                                         0   
8                                         0   
9                                         0   
10                                        0   
11                                        0   
12                                        0   
13                                        0   
14                                        0   
15                         

In [5]:
df.columns

Index(['SSL SCORE', 'PREDICTOR RAT AGE AT LATEST ARREST',
       'PREDICTOR RAT VICTIM SHOOTING INCIDENTS',
       'PREDICTOR RAT VICTIM BATTERY OR ASSAULT',
       'PREDICTOR RAT ARRESTS VIOLENT OFFENSES',
       'PREDICTOR RAT GANG AFFILIATION', 'PREDICTOR RAT NARCOTIC ARRESTS',
       'PREDICTOR RAT TREND IN CRIMINAL ACTIVITY', 'PREDICTOR RAT UUW ARRESTS',
       'SEX CODE CD', 'RACE CODE CD', 'WEAPON I', 'DRUG I', 'AGE GROUP',
       'AGE TO', 'STOP ORDER NO', 'PAROLEE I', 'LATEST DATE', 'LATEST DIST',
       'MAJORITY DIST', 'DLST', 'LATEST DIST RES', 'WEAPONS ARR CNT',
       'LATEST WEAPON ARR DATE', 'NARCOTICS ARR CNT',
       'LATEST NARCOTIC ARR DATE', 'IDOC RES CITY', 'IDOC RES STATE CODE',
       'IDOC RES ZIP CODE', 'IDOC CPD DIST', 'CPD ARREST I',
       'DOMESTIC ARR CNT', 'LATEST DOMESTIC ARR DATE', 'AGE CURR',
       'SSL LAST PTV DATE', 'TRAP STATUS', 'RAW SSL SCORE', 'HEAT SCORE',
       'RAW_HEAT_SCORE', 'STATUS I', 'PRE RAW HEAT SCORE', 'TRAP FLAGS',
       'SSL FL

# PREDICTING TREND
Below we are interested in predicting 'PREDICTOR RAT TREND IN CRIMINAL ACTIVITY'.

In [7]:
Y = df['PREDICTOR RAT TREND IN CRIMINAL ACTIVITY'].values

In [23]:
X = df[['LATEST DATE','WEAPONS ARR CNT','LATEST WEAPON ARR DATE','NARCOTICS ARR CNT', 'LATEST NARCOTIC ARR DATE',\
       'DOMESTIC ARR CNT', 'LATEST DOMESTIC ARR DATE', 'SSL LAST PTV DATE']].values
X.shape

(398684, 8)

In [39]:
[np.isnan(x) for x in X]

[array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True, False, False,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([False,  True,  True, False, False,  True,  True, False]),
 array([False, False, False,  True,  True,  True,  True,  True]),
 array([False,  True,  True,  True,  True,  True,  True,  True]),
 array([Fa

In [25]:
np.nan

nan

In [62]:
f = lambda x: -np.inf if np.isnan(x) else x
X = np.array([[f(i) for i in line] for line in X])

In [48]:
X[100300]

array([2013.,   nan,   nan,   nan,   nan,   nan,   nan,   nan])

In [37]:
isnan

NameError: name 'isnan' is not defined

In [41]:
np.inf

inf